Nodejs/week3
sofiiadidovych/hyf-homework pull request #20
Opened 2021-02-18 17:50 UTC by sofiiadidovych

2021-02-19 18:30 UTC, Ekamba requested changes
Hi @sofiiadidovych , as sum mean addition I thing you need to change the name of that variable at line 22 and below. Also you don't need a post request here as there is no logic that is taking care of it and your data is not going anywhere

2021-03-22 12:20 UTC, sofiiadidovych commented
Hi @Ekamba! Thank you very much for your review, and sorry for my silence. I have questions about your request for changes:
1) I meant addition at line 22, because I am substracting the sum of all parameters from the first parameter (because we can have an infinite number of parameters);
2) We had to do a post method and check it in postman:
https://github.com/HackYourFuture-CPH/node.js/tree/master/week3/homework-template#getting-data-through-the-request-body-using-post
So, please tell me if my logic is not correct. Thank you!

2021-03-22 17:42 UTC, Ekamba commented
All good, @sofiiadidovych . I get the point now.

2021-03-22 17:43 UTC, Ekamba approved these changes

2021-03-22 17:46 UTC, merged